"""
Generate pre-signed client installer and register broker user via mosquitto_passwd.
"""
from __future__ import annotations

import secrets
import subprocess
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .state import State

INSTALL_SH_TEMPLATE = '''#!/bin/sh
# MMDVM-Link client installer (generated by Central Controller)
# Do not edit NODE_ID, ONE_TIME_TOKEN, SERVER_ADDR manually.
# WARNING: This script contains a one-time token. Distribute/store it securely and delete after use.

set -e
NODE_ID="{node_id}"
ONE_TIME_TOKEN="{one_time_token}"
SERVER_ADDR="{server_addr}"

echo "NODE_ID=$NODE_ID"
echo "SERVER_ADDR=$SERVER_ADDR"
# Install steps (placeholder): install MQTT client, configure with above vars, run client.
# Client must: connect with username=$NODE_ID password=$ONE_TIME_TOKEN, then publish to nodes/bind with hardware_serial.
'''


def _generate_id() -> str:
    return "node_" + secrets.token_hex(6)


def _generate_token() -> str:
    return secrets.token_urlsafe(32)


def generate(
    state: State,
    output_dir: str | Path,
    server_addr: str,
    broker_password_file: str | Path,
) -> Path:
    """
    Generate unique node_id and one_time_token, write installer script, register broker user,
    record in state. Returns path to the generated script.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    node_id = _generate_id()
    one_time_token = _generate_token()
    state.add_issued(node_id, one_time_token)

    out_path = output_dir / f"install_{node_id}.sh"
    try:
        content = INSTALL_SH_TEMPLATE.format(
            node_id=node_id,
            one_time_token=one_time_token,
            server_addr=server_addr,
        )
        out_path.write_text(content, encoding="utf-8")
        try:
            # Restrict permissions because the script contains a one-time token.
            out_path.chmod(0o700)
        except OSError:
            # Windows / restrictive filesystems: best-effort only.
            pass

        broker_path = Path(broker_password_file)
        broker_path.parent.mkdir(parents=True, exist_ok=True)
        args = ["mosquitto_passwd"]
        if not broker_path.exists():
            args.append("-c")
        args.extend([str(broker_path), node_id])
        subprocess.run(
            args,
            check=True,
            capture_output=True,
            timeout=10,
            input=f"{one_time_token}\n{one_time_token}\n",
            text=True,
        )
    except FileNotFoundError as e:
        state.remove_issued(node_id)
        if out_path.exists():
            out_path.unlink(missing_ok=True)
        msg = (
            "Cannot generate installer because 'mosquitto_passwd' is not available.\n"
            "- Install Mosquitto (includes mosquitto_passwd)\n"
            "- Ensure 'mosquitto_passwd' is on PATH, or run the server on the machine where it's installed."
        )
        raise InstallerGenError(msg) from e
    except subprocess.TimeoutExpired as e:
        state.remove_issued(node_id)
        if out_path.exists():
            out_path.unlink(missing_ok=True)
        msg = (
            "Timed out while running 'mosquitto_passwd'.\n"
            "- Verify the broker password file path is on a local disk and writable\n"
            "- Retry after ensuring the server has filesystem permissions"
        )
        raise InstallerGenError(msg) from e
    except subprocess.CalledProcessError as e:
        state.remove_issued(node_id)
        if out_path.exists():
            out_path.unlink(missing_ok=True)
        msg = (
            "Failed to add broker user via 'mosquitto_passwd'.\n"
            "- Check BROKER_PASSWORD_FILE path and write permissions\n"
            "- Ensure the directory exists and is writable by the server user\n"
            f"- mosquitto_passwd exit code: {e.returncode}"
        )
        raise InstallerGenError(msg) from e
    except Exception:
        state.remove_issued(node_id)
        if out_path.exists():
            out_path.unlink(missing_ok=True)
        raise

    return out_path


class InstallerGenError(RuntimeError):
    pass
